CREATE TABLE IF NOT EXISTS palavras (
    id SERIAL PRIMARY KEY,
    palavra VARCHAR(100) NOT NULL,
    dica VARCHAR(255) NOT NULL
);

INSERT INTO palavras (palavra, dica) VALUES
('CANGURU', 'Animal popular da Austrália'),
('PROTETOR SOLAR', 'Proteção contra o sol'),
('PALMEIRAS', 'Time com o mesmo nome de uma árvore'),
('MESSI', 'Baixinho argentino bom de bola'),
('FLÓRIDA', 'Estado onde se localiza a Disney'),
('BRASIL', 'País com a maior floresta tropical do mundo'),
('TELESCÓPIO', 'Usado para observar estrelas'),
('OLIMPÍADAS', 'Realizadas a cada 4 anos'),
('EIFFEL', 'Monumento em Paris, França'),
('HALLOWEEN', 'Festa comemorada no dia 31 de outubro'),
('PIRÂMIDE', 'Monumentos no Cairo, Egito'),
('SAARA', 'Maior deserto quente do mundo'),
('ARROZ', 'Se come com feijão'),
('ITÁLIA', 'País em forma de bota'),
('IRA', 'Pecado capital'),
('CAVALOS', 'Ficam dentro do motor do carro'),
('GRANIZO', 'Pedras de gelo que caem das nuvens'),
('MÚSICA', 'Melhor amiga dos ouvidos'),
('CHOCOLATE', 'Doce feito a partir do cacau'),
('CACHOEIRA', 'Queda de água de grande altura'),
('GALO', 'Marido da galinha'),
('ORCA', 'A baleia assassina'),
('LUIGI', 'Irmão do Mário'),
('PASTEL', 'Tem de carne, queijo, pizza etc'),
('VENTILADOR', 'Aliado contra o calor'),
('BOB', 'Esponja, Marley, Construtor'),
('PILHA', 'Tipo de bateria'),
('HIPERTROFIA', 'Consequência da musculação'),
('LARANJA', 'Pode ser fruta ou cor'),
('PARREIRA', 'Pé de uva'),
('GATO', 'Garfield, Félix e Tom'),
('PATO', 'Ave presente no nome de um jogador de futebol brasileiro'),
('THOMAS', 'Nome do trem do desenho animado'),
('COYOTE', 'Perseguidor do papa-léguas'),
('FOTOSSÍNTESE', 'Processo pelo qual plantas produzem energia'),
('TSUNAMI', 'Onda gigante que pode devastar costas'),
('VULCÃO', 'Montanha que pode entrar em erupção'),
('METEORO', 'Pedra do espaço que brilha ao entrar na atmosfera'),
('ECOSSISTEMA', 'Conjunto de seres vivos e seu ambiente'),
('SAMURAI', 'Guerreiro japonês de honra'),
('REVOLUÇÃO', 'Mudança radical na sociedade ou governo'),
('TESOURA', 'Usada para cortar cabelo e papel'),
('ALGORITMO', 'Série de passos para resolver um problema'),
('HACKER', 'Pessoa que explora sistemas de computador'),
('ROBÓTICA', 'Ciência de criar máquinas autônomas'),
('MARATONA', 'Corrida de longa distância'),
('SURF', 'Esporte sobre ondas do mar'),
('GOLFE', 'Jogo com tacos e bolas em campo aberto'),
('ESQUI', 'Deslizar pela neve com pranchas'),
('CAFÉ', 'Bebida energética matinal'),
('CHAVE', 'Objeto que abre portas'),
('RELÓGIO', 'Instrumento que mede o tempo'),
('VARANDA', 'Espaço externo para relaxar'),
('COZINHA', 'Lugar onde se preparam refeições'),
('ROMANCE', 'História fictícia longa'),
('PINTURA', 'Arte de usar tintas para criar imagens'),
('BALÉ', 'Dança clássica com movimentos graciosos'),
('HIMALAIA', 'A maior cadeia montanhosa do mundo'),
('AMAZÔNIA', 'A maior floresta tropical do planeta'),
('DESERTO', 'Região árida com pouca chuva'),
('OCEANO', 'Vasta extensão de água salgada'),
('PRAIA', 'Lugar onde mar e terra se encontram'),
('FÓSSIL', 'Restos de vida antiga preservados'),
('TÊNIS', 'Esporte jogado com raquetes'),
('DNA', 'Molécula que carrega informação genética'),
('BASQUETE', 'Esporte que se arremessa a bola na cesta'),
('IRMÃOS', 'Filhos da mesma mãe'),
('HÓQUEI', 'Esporte praticado no gelo'),
('POMADA', 'Tipo de modelador de cabelo'),
('FILOSOFIA', 'Estudo das questões fundamentais da existência'),
('MUSEU', 'Lugar onde se expõe arte e história'),
('ARQUITETURA', 'Arte de projetar edifícios'),
('SATÉLITE', 'Objeto que orbita a Terra ou outro corpo celeste'),
('PAPEL', 'Material para escrever ou desenhar'),
('FESTIVAL', 'Evento com música, comida e entretenimento'),
('TURISMO', 'Atividade de visitar lugares novos'),
('MILENAR', 'Que tem mil anos de idade'),
('LEGADO', 'Herança ou tradição passada adiante'),
('PANORAMA', 'Vista ampla e extensa'),
('HIBERNAR', 'Dormir durante o inverno para economizar energia'),
('VOO', 'Ato de voar'),
('CULINÁRIA', 'Arte de cozinhar'),
('MEDITAÇÃO', 'Prática de aquietar a mente'),
('ELEIÇÃO', 'Processo de escolher líderes por voto'),
('FURACÃO', 'Tempestade tropical severa'),
('CONSTITUIÇÃO', 'Documento que define as leis básicas de um país'),
('IMUNIDADE', 'Proteção natural ou adquirida contra doenças'),
('ZEPPELIN', 'Dirigível de grande porte'),
('MOEDA', 'Unidade de valor usada no comércio'),
('CALIGRAFIA', 'Arte de escrever belamente'),
('DINAMITE', 'Explosivo inventado por Nobel'),
('GEOLOGIA', 'Estudo das rochas e da Terra'),
('INFINITO', 'Conceito sem fim ou limite'),
('LABIRINTO', 'Estrutura com muitos caminhos e saídas'),
('MAMUTE', 'Grande mamífero extinto da era do gelo'),
('ORQUESTRA', 'Grupo de músicos que tocam juntos'),
('PODCAST', 'Programa de áudio para streaming'),
('VAQUEIRO', 'Tradução de Cowboy'),
('COMEMORAÇÃO', 'Ato feito pelo jogador após um gol'),
('ASTRONAUTA', 'Viaja para o espaço'),
('GUITARRA', 'Um dos instrumentos de corda de uma banda de rock');
